apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Call instrumented action
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Call instrumented action
        uses: gmaxey/evidence/instrumented-action-example
        in: Some text to pass on
