apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Call instrumented action
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Call instrumented action
        uses: cloudbees-io/publish-evidence-item/instrumented-action-example
        with:
          in: Some text to pass on