apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: matrix
on:
  workflow_dispatch:
jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "matrix job step"
  parallel-job: # run in parallel to the matrix jobs
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "parallel job step"    
  clean-up: # Wait for all jobs to complete
    needs: example_matrix
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "needs job step"

