apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: get-workflow-details
on:
  workflow_dispatch:

env:
  PAT: "${{ secrets.PAT }}"
  CLOUDBEES_API_URL: ${{ cloudbees.api.url }}

jobs:
  build:
    steps:
      - name: Get workflow details
        id: orgcomp
        uses: docker://figured/alpine-curl-jq-bash
        shell: bash
        run: |
          echo ${{ cloudbees.run_id }}
          RESPONSE=$(curl -X 'GET'  ${{cloudbees.api.url}}/v1/resources/8f2a2b97-7de5-4b00-b8f7-e964add3c585?parents=true \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.PAT }}')
          echo "$RESPONSE" | jq -c -r '.parents[] | select(.type=="RESOURCE_TYPE_ORGANIZATION") | .id' | head -1  | tr -d '\n' > "$CLOUDBEES_OUTPUTS/orgId"
          echo "$RESPONSE" | jq -c -r '.parents[] | select(.type=="RESOURCE_TYPE_REPOSITORY") | .id'  | tr -d '\n' > "$CLOUDBEES_OUTPUTS/componentId"
          echo "resources/$(cat $CLOUDBEES_OUTPUTS/orgId)/services/$(cat $CLOUDBEES_OUTPUTS/componentId)"
      - name: Get component IDs from the application
        id: components
        uses: docker://figured/alpine-curl-jq-bash
        shell: bash
        env:
          ORGID: >-
            ${{ steps.orgcomp.outputs.orgId}}
          COMPONENTID: >-
            ${{ steps.orgcomp.outputs.componentId}}
        run: |
          echo curl -X 'GET' ${CLOUDBEES_API_URL}/v1/resources/${ORGID}/services/${COMPONENTID}    --header 'Content-Type: application/json'       --header "Authorization: Bearer $PAT"
          curl -X 'GET' ${CLOUDBEES_API_URL}/v1/resources/${{ steps.orgcomp.outputs.orgId}}/services/${{ steps.orgcomp.outputs.componentId}}    --header 'Content-Type: application/json'       --header "Authorization: Bearer $PAT"
          COMPONENT_IDS="$(curl -X 'GET' ${CLOUDBEES_API_URL}/v1/resources/${{ steps.orgcomp.outputs.orgId}}/services/${{ steps.orgcomp.outputs.componentId}}    --header 'Content-Type: application/json'       --header "Authorization: Bearer $PAT" | jq -r '.service.linkedComponentIds[]')"
          echo $COMPONENT_IDS > "$CLOUDBEES_OUTPUTS/componentIds"     
