apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: get-workflow-details
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Get workflow details
        uses: docker://figured/alpine-curl-jq-bash
        shell: bash
        run: |
          echo ${{ cloudbees.run_id }}
          curl -X 'GET'  ${CLOUDBEES_API_URL}/v1/resources/${{ cloudbees.run_id }}?parents=true \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ cloudbees.api.token }}'
