apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: get-workflow-details
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Get workflow details
        uses: docker://figured/alpine-curl-jq-bash
        shell: bash
        run: |
          echo ${{ cloudbees.run_id }}
          REPSONSE=$(curl -X 'GET'  ${{cloudbees.api.url}}/v1/resources/8f2a2b97-7de5-4b00-b8f7-e964add3c585?parents=true \
          --header 'Content-Type: application/json' \
          --header 'Authorization: Bearer ${{ secrets.PAT }}')
          echo "$REPSONSE" | jq -c -r '.parents[] | select(.type=="RESOURCE_TYPE_ORGANIZATION") | .id' | head -1 > "$CLOUDBEES_OUTPUTS/orgId" | tr -d '\n'
          echo "$REPSONSE" | jq -c -r '.parents[] | select(.type=="RESOURCE_TYPE_REPOSITORY") | .id' > "$CLOUDBEES_OUTPUTS/componentId" | tr -d '\n'
          echo "resources/$(cat $CLOUDBEES_OUTPUTS/orgId)/services/$(cat $CLOUDBEES_OUTPUTS/componentId)"
