apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: outputs-beyond-needs
on:
  workflow_dispatch:
jobs:
  A:
    outputs:
      Aout: ${{ steps.out.outputs.Aout }}
    steps:
      - name: Say hello
        id: out
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Aout value" > "$CLOUDBEES_OUTPUTS/Aout"
  B:
    outputs:
      Aout: ${{ steps.out.outputs.Aoutt }}
    needs: A
    steps:
      - name: Say hello
        id: out
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{needs.A.outputs.Aout}}" > "$CLOUDBEES_OUTPUTS/Aout"
  C:
    needs: B
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "${{needs.B.outputs.Aout}}"     
