apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Evidence Action
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - name: Evidence markdown examples
        id: evidence_step
        uses: cloudbees-io/publish-evidence-item
        with:
          content: |
            Step: ${{ cloudbees.step_id }}
            
            ## List
            - Run ID: ${{ cloudbees.run_id }}
            - [backend.tar](https://ourcompany.com/repo/backend.tar)

            ## Numbered list
            1. Test 1 - Frontend
            1. Test 2 - Backend
            1. Test 3 - Data layer

            ## Code
            ```
            jobs:
              build:
                steps:
                - Compile
            ```

            ## Table
            | Test     | Reults  |
            | -------- | ------- |
            | Test 1   | PASS    |
            | Test 2   | FAIL    |
            | Test 3   | PASS    |

            > Context and memory play

            ## Format
            - **bold text**
            - _italics_
            - ~~strike through~~

            ![CloudBees](https://www.cloudbees.com/)
