apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test Evidence Action
on:
  workflow_dispatch:
jobs:
  build:
    steps:
      - uses: cloudbees-io/publish-evidence-item
        name: Evidence markdown examples
        id: evidence_step
        with:
          content: |-
            Step: ${{ cloudbees.run_id }}
            ## List
            - Run ID: ${{ cloudbees.run_id }}
            - [backend.tar](https://ourcompany.com/repo/backend.tar)

            ## Numbered list
            1. Test 1 - Frontend
            1. Test 2 - Backend
            1. Test 3 - Data layer

            ## Code
            ```
            jobs:
              build:
                steps:
                - Compile
            ```

            ## Table
            | Test     | Reults  |
            | -------- | ------- |
            | Test 1   | PASS    |
            | Test 2   | FAIL    |
            | Test 3   | PASS    |

            > Quoted text

            ## Format
            - **bold text**
            - _italics_
            - ~~strike through~~

            ![CloudBees Platform](https://www.cloudbees.com/videos/new-cloud-native-devsecops-platform-training-creating-your-first-component)
            
      - uses: cloudbees-io/publish-evidence-item@v1
        name: Second evidence step
        with:
          content: |-
            Simple text
            - bullet 1
            - bullet 2
